In [2]:
import torch
import torchvision
import torch.nn as nn

In [7]:
model= torchvision.models.alexnet(pretrained= True)

In [3]:
from MAS_model import *


In [23]:
type(model)

torchvision.models.alexnet.AlexNet

In [18]:
model

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [48]:
in_features = model.classifier[-1].in_features

In [49]:
in_features

4096

In [50]:
del model.classifier[-1]

In [51]:
model

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [52]:
model.state_dict()

OrderedDict([('features.0.weight',
              tensor([[[[ 1.1864e-01,  9.4069e-02,  9.5435e-02,  ...,  5.5822e-02,
                          2.1575e-02,  4.9963e-02],
                        [ 7.4882e-02,  3.8940e-02,  5.2979e-02,  ...,  2.5709e-02,
                         -1.1299e-02,  4.1590e-03],
                        [ 7.5425e-02,  3.8779e-02,  5.4930e-02,  ...,  4.3596e-02,
                          1.0225e-02,  1.3251e-02],
                        ...,
                        [ 9.3155e-02,  1.0374e-01,  6.7547e-02,  ..., -2.0277e-01,
                         -1.2839e-01, -1.1220e-01],
                        [ 4.3544e-02,  6.4916e-02,  3.6164e-02,  ..., -2.0248e-01,
                         -1.1376e-01, -1.0719e-01],
                        [ 4.7369e-02,  6.2543e-02,  2.4758e-02,  ..., -1.1844e-01,
                         -9.5567e-02, -8.3890e-02]],
              
                       [[-7.2634e-02, -5.7996e-02, -8.0661e-02,  ..., -6.0304e-04,
                         -2

In [53]:
model2 = models.alexnet(pretrained=False)

In [54]:
model2.state_dict()

OrderedDict([('features.0.weight',
              tensor([[[[-2.8722e-02,  3.4470e-02, -3.5194e-02,  ..., -2.5757e-02,
                         -2.9826e-02, -2.9037e-02],
                        [ 4.1150e-02,  1.0017e-02,  4.3639e-02,  ...,  3.1586e-02,
                         -4.0086e-02, -5.1183e-03],
                        [-1.0456e-02,  4.9969e-02,  4.4593e-02,  ..., -1.8659e-02,
                          2.7292e-02, -3.2828e-02],
                        ...,
                        [-5.1243e-02, -3.3669e-02,  2.5065e-02,  ...,  4.5917e-02,
                         -3.1944e-02,  3.4792e-02],
                        [-1.8530e-02, -4.9638e-02,  4.2736e-02,  ..., -4.0126e-02,
                          2.2983e-02, -4.9928e-02],
                        [-3.4676e-02,  2.2727e-03,  4.4664e-02,  ...,  3.9591e-02,
                          1.9255e-02, -4.1549e-02]],
              
                       [[ 3.8711e-02, -9.9574e-03, -1.4311e-02,  ..., -5.7247e-03,
                         -1

In [42]:
deeps.xmodel.classifier[-1]

AttributeError: 'SharedModel' object has no attribute 'xmodel'

In [60]:
a = SharedModel()

In [87]:
a.state_dict()

OrderedDict([('model.features.0.weight',
              tensor([[[[ 1.1864e-01,  9.4069e-02,  9.5435e-02,  ...,  5.5822e-02,
                          2.1575e-02,  4.9963e-02],
                        [ 7.4882e-02,  3.8940e-02,  5.2979e-02,  ...,  2.5709e-02,
                         -1.1299e-02,  4.1590e-03],
                        [ 7.5425e-02,  3.8779e-02,  5.4930e-02,  ...,  4.3596e-02,
                          1.0225e-02,  1.3251e-02],
                        ...,
                        [ 9.3155e-02,  1.0374e-01,  6.7547e-02,  ..., -2.0277e-01,
                         -1.2839e-01, -1.1220e-01],
                        [ 4.3544e-02,  6.4916e-02,  3.6164e-02,  ..., -2.0248e-01,
                         -1.1376e-01, -1.0719e-01],
                        [ 4.7369e-02,  6.2543e-02,  2.4758e-02,  ..., -1.1844e-01,
                         -9.5567e-02, -8.3890e-02]],
              
                       [[-7.2634e-02, -5.7996e-02, -8.0661e-02,  ..., -6.0304e-04,
                     

In [78]:
a.params

{}

In [79]:
SharedModel(a)

TypeError: __init__() takes 1 positional argument but 2 were given

In [82]:
a= SharedModel()

In [84]:
a.params

{}

In [86]:
    a.xmodel

AttributeError: 'SharedModel' object has no attribute 'xmodel'

In [93]:
for param in a.model.classifier.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0040,  0.0061,  0.0134,  ..., -0.0003, -0.0022, -0.0093],
        [ 0.0013,  0.0020,  0.0028,  ...,  0.0053,  0.0002, -0.0145],
        [-0.0185, -0.0145, -0.0198,  ..., -0.0003, -0.0012,  0.0191],
        ...,
        [-0.0063,  0.0026, -0.0084,  ..., -0.0079,  0.0055,  0.0067],
        [-0.0115, -0.0055, -0.0092,  ..., -0.0039, -0.0048, -0.0099],
        [ 0.0026, -0.0148, -0.0016,  ...,  0.0050,  0.0052, -0.0045]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0324,  0.0621, -0.0557,  ..., -0.0248,  0.0185,  0.0095],
       requires_grad=True)
Parameter containing:
tensor([[-0.0107, -0.0015,  0.0057,  ...,  0.0026, -0.0010, -0.0087],
        [-0.0279,  0.0168, -0.0162,  ..., -0.0079, -0.0049, -0.0219],
        [-0.0112, -0.0184,  0.0073,  ...,  0.0013,  0.0050,  0.0055],
        ...,
        [-0.0027, -0.0146,  0.0057,  ...,  0.0250, -0.0042, -0.0009],
        [ 0.0066,  0.0094,  0.0232,  ...,  0.0060, -0.0029, -0.0042],
        [ 0.01

In [94]:
class shared_model(nn.Module):
	def __init__(self, model):
		super(shared_model, self).__init__()
		self.tmodel = models.alexnet(pretrained = True)
		self.reg_params = {}

	def forward(self, x):
		return self.tmodel(x)

In [95]:
b=shared_model(a)

In [96]:
b

shared_model(
  (tmodel): AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU(inplace=True)
      (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (9): ReLU(inplace=True)
      (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
    (classifier): Sequential(
      (0): Dropout(p=0.5, inplace=False)
   

In [98]:
c = SharedModel(a)

In [99]:
c

SharedModel(
  (xmodel): AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU(inplace=True)
      (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (9): ReLU(inplace=True)
      (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
    (classifier): Sequential(
      (0): Dropout(p=0.5, inplace=False)
    

In [8]:
a =SharedModel(model)

In [9]:
a

SharedModel(
  (xmodel): AlexNet(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
      (1): ReLU(inplace=True)
      (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
      (4): ReLU(inplace=True)
      (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (7): ReLU(inplace=True)
      (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (9): ReLU(inplace=True)
      (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
    (classifier): Sequential(
      (0): Dropout(p=0.5, inplace=False)
    

In [19]:
a.xmodel.features._modules

OrderedDict([('0',
              Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))),
             ('1', ReLU(inplace=True)),
             ('2',
              MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)),
             ('3',
              Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))),
             ('4', ReLU(inplace=True)),
             ('5',
              MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)),
             ('6',
              Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))),
             ('7', ReLU(inplace=True)),
             ('8',
              Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))),
             ('9', ReLU(inplace=True)),
             ('10',
              Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))),
             ('11', ReLU(inplace=True)),
             ('12',
              MaxPool2d(kernel_size=3, stride

In [26]:
temp_list =[]
for key in a.xmodel.features._modules:
        if(type(a.xmodel.features._modules[key])==torch.nn.modules.conv.Conv2d):
            temp_list.append(key)

In [23]:
for key in a.xmodel.features._modules:
    print(key)

0
1
2
3
4
5
6
7
8
9
10
11
12


In [33]:
v ={}
name1 = "Deepansh"
name2= "goyal"
v.update(str(name1) =name2)

SyntaxError: keyword can't be an expression (<ipython-input-33-76251e31e73d>, line 4)

In [44]:
use_gpu = False

In [43]:
 for name,params in a.xmodel.named_parameters():
    print(name,"name")
    print(params)

features.0.weight name
Parameter containing:
tensor([[[[ 1.1864e-01,  9.4069e-02,  9.5435e-02,  ...,  5.5822e-02,
            2.1575e-02,  4.9963e-02],
          [ 7.4882e-02,  3.8940e-02,  5.2979e-02,  ...,  2.5709e-02,
           -1.1299e-02,  4.1590e-03],
          [ 7.5425e-02,  3.8779e-02,  5.4930e-02,  ...,  4.3596e-02,
            1.0225e-02,  1.3251e-02],
          ...,
          [ 9.3155e-02,  1.0374e-01,  6.7547e-02,  ..., -2.0277e-01,
           -1.2839e-01, -1.1220e-01],
          [ 4.3544e-02,  6.4916e-02,  3.6164e-02,  ..., -2.0248e-01,
           -1.1376e-01, -1.0719e-01],
          [ 4.7369e-02,  6.2543e-02,  2.4758e-02,  ..., -1.1844e-01,
           -9.5567e-02, -8.3890e-02]],

         [[-7.2634e-02, -5.7996e-02, -8.0661e-02,  ..., -6.0304e-04,
           -2.5309e-02,  2.5471e-02],
          [-6.9042e-02, -6.7562e-02, -7.6367e-02,  ..., -3.9616e-03,
           -3.0402e-02,  1.0477e-02],
          [-9.9517e-02, -8.5592e-02, -1.0521e-01,  ..., -2.6587e-02,
           -2

In [49]:
device = torch.device("cuda:0" if use_gpu else "cpu")

freeze_layers= []
reg_params = {}

for name, param in a.xmodel.named_parameters():
    if not name in freeze_layers:

        print ("Initializing omega values for layer", name)
        omega = torch.zeros(param.size())
        omega = omega.to(device)

        init_val = param.data.clone()
        param_dict = {}

        #for first task, omega is initialized to zero
        param_dict['omega'] = omega
        param_dict['init_val'] = init_val

        #the key for this dictionary is the name of the layer
        reg_params[param] = param_dict

a.reg_params = reg_params


Initializing omega values for layer features.0.weight
Initializing omega values for layer features.0.bias
Initializing omega values for layer features.3.weight
Initializing omega values for layer features.3.bias
Initializing omega values for layer features.6.weight
Initializing omega values for layer features.6.bias
Initializing omega values for layer features.8.weight
Initializing omega values for layer features.8.bias
Initializing omega values for layer features.10.weight
Initializing omega values for layer features.10.bias
Initializing omega values for layer classifier.1.weight
Initializing omega values for layer classifier.1.bias
Initializing omega values for layer classifier.4.weight
Initializing omega values for layer classifier.4.bias
Initializing omega values for layer classifier.6.weight
Initializing omega values for layer classifier.6.bias
